version: '3.8'

services:
  collection:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'database'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'db_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'db_password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted volumes
    volumes:
      - datafiles:/var/lib/mysql
volumes:
  datafiles: